### ISSUE TITLE
Can't connect my sparrow wallet to Electrum

### ISSUE THREAD

**Issue by admzvk** [raspibolt/raspibolt#1328]
### Describe the issue
I followed the guide, installed Bitcoin Core, installed Electrum. Bitcoin Core is synchronized, Electrum is indexed.
When I wanted to connect from Sparrow wallet, it got stucked on message "Connecting to ssl://192.168.2.2:50002..."

Nginx is configured.
Ufw rule applied.
Netcat from RPi:
`admin@raspibolt:~ $ ncat -v --ssl localhost 50002
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connection to ::1 failed: Connection refused.
Ncat: Trying next address...
Ncat: Subject: CN=localhost
Ncat: Issuer: CN=localhost
Ncat: SHA-1 fingerprint: B102...
Ncat: Certificate verification failed (self signed certificate).
Ncat: SSL connection to 127.0.0.1:50002.
Ncat: SHA-1 fingerprint: B102...`
Netcat from computer:
`janedoe@Janes-Pro ~ % nc -vz -vvv 192.168.2.2 50002
Connection to 192.168.2.2 port 50002 [tcp/*] succeeded!`

### Location in guide
[Link to the corresponding page and section on <https://raspibolt.org>](https://raspibolt.org/guide/bitcoin/electrum-server.html)

### Environment
 - Hardware platform: Rpi 4B 4GB
 - Operating system: Raspberry Pi OS Lite 64bit
 - Version: Sparrow 1.7.8; Electrs 0.10.0

### Additional context
Debug logs from sparrow:
`2023-07-26 23:25:22,448 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting server version
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getServerVersion$1(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at ssl://192.168.2.2:50002
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
Caused by: java.io.IOException: Could not connect to server at ssl://192.168.2.2:50002
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted
2023-07-26 23:30:03,126 ERROR [JavaFX Application Thread] c.s.s.p.ServerPreferencesController [null:-1] Connection error
com.sparrowwallet.sparrow.net.ElectrumServerRpcException: Error getting server version
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer.getServerVersion(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ConnectionService$1.call(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@18/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.sparrowwallet.sparrow.net.ServerException: Retries exhausted
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.RetryLogic.getResult(Unknown Source)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: I/O error during a request processing
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeRequest(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.executeAndConvert(Unknown Source)
	at simple.json.rpc.client@1.3/com.github.arteam.simplejsonrpc.client.builder.RequestBuilder.execute(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.SimpleElectrumServerRpc.lambda$getServerVersion$1(Unknown Source)
	... 13 common frames omitted
Caused by: java.io.IOException: Error reading response: Could not connect to server at ssl://192.168.2.2:50002
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readResponse(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.pass(Unknown Source)
	... 17 common frames omitted
Caused by: java.io.IOException: Could not connect to server at ssl://192.168.2.2:50002
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readInputStream(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.TcpTransport.readInputLoop(Unknown Source)
	at com.sparrowwallet.sparrow@1.7.8/com.sparrowwallet.sparrow.net.ElectrumServer$ReadRunnable.run(Unknown Source)
	... 1 common frames omitted`

Debug logs from electrs
`Jul 26 23:30:22 raspibolt systemd[1]: Started Electrs daemon.
Jul 26 23:30:22 raspibolt electrs[938]: Starting electrs 0.10.0 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/electrs/db/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.10.0 (Electrum Rust Server)!", signet_magic: f9beb4d9, args: [] }
Jul 26 23:30:22 raspibolt electrs[938]: [2023-07-26T21:30:22.754Z DEBUG tiny_http] Server listening on 127.0.0.1:4224
Jul 26 23:30:22 raspibolt electrs[938]: [2023-07-26T21:30:22.755Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Jul 26 23:30:22 raspibolt electrs[938]: [2023-07-26T21:30:22.755Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
Jul 26 23:30:22 raspibolt electrs[938]: [2023-07-26T21:30:22.756Z DEBUG tiny_http] Running accept thread
Jul 26 23:30:24 raspibolt electrs[938]: [2023-07-26T21:30:24.146Z INFO  electrs::db] "/data/electrs/db/bitcoin": 676 SST files, 59.400520719 GB, 5.251835644 Grows
Jul 26 23:30:24 raspibolt electrs[938]: [2023-07-26T21:30:24.147Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
Jul 26 23:30:27 raspibolt electrs[938]: [2023-07-26T21:30:27.917Z INFO  electrs::chain] loading 800401 headers, tip=000000000000000000012746133de1333a3524b05e6b57e1c717729a9138b86f
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.465Z INFO  electrs::chain] chain updated: tip=000000000000000000012746133de1333a3524b05e6b57e1c717729a9138b86f, height=800401
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.499Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.578Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.607Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.632Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.659Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
Jul 26 23:30:31 raspibolt electrs[938]: [2023-07-26T21:30:31.850Z DEBUG electrs::p2p] peer version: VersionMessage { version: 70016, services: ServiceFlags(1033), timestamp: 1690407031, receiver: Address {services: ServiceFlags(NONE), address: 0.0.0.0, port: 0}, sender: Address {services: ServiceFlags(NETWORK|WITNESS|NETWORK_LIMITED), address: 0.0.0.0, port: 0}, nonce: 17412913723906820507, user_agent: "/Satoshi:25.0.0/", start_height: 800403, relay: true }
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.045Z DEBUG electrs::p2p] got 2 new headers
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.045Z INFO  electrs::index] indexing 2 blocks: [800402..800403]
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.045Z DEBUG electrs::p2p] loading 2 blocks
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.323Z DEBUG electrs::index] writing 26604 funding and 11989 spending rows from 6238 transactions, 2 blocks
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.372Z INFO  electrs::chain] chain updated: tip=00000000000000000001cae6c1308db7059495584f39f88c25bf5c4c8b9bdf12, height=800403
Jul 26 23:30:32 raspibolt electrs[938]: [2023-07-26T21:30:32.662Z DEBUG electrs::p2p] got 0 new headers
Jul 26 23:30:33 raspibolt electrs[938]: [2023-07-26T21:30:33.031Z INFO  electrs::db] starting config compaction
Jul 26 23:30:33 raspibolt electrs[938]: [2023-07-26T21:30:33.110Z INFO  electrs::db] starting headers compaction
Jul 26 23:30:37 raspibolt electrs[938]: [2023-07-26T21:30:37.269Z INFO  electrs::db] starting txid compaction
Jul 26 23:30:45 raspibolt electrs[938]: [2023-07-26T21:30:45.508Z DEBUG electrs::server] 0: recv {"jsonrpc":"2.0","method":"server.version","params":["Sparrow","1.4"],"id":1}
Jul 26 23:40:45 raspibolt electrs[938]: [2023-07-26T21:40:45.766Z DEBUG electrs::server] 0: disconnected
Jul 26 23:40:46 raspibolt electrs[938]: [2023-07-26T21:40:46.021Z DEBUG electrs::server] 1: recv {"jsonrpc":"2.0","method":"server.version","params":["Sparrow","1.4"],"id":1}
`

**Comment by admzvk** [comment]
Day after, everything just started to work. Do not know where were the problem, but it worth to wait a bit after indexing I guess.
